# Generated by Django 3.0.6 on 2020-06-03 05:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_promo_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promo_action',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
