# Generated by Django 3.0.6 on 2020-06-03 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_promoactionproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
            ],
            options={
                'verbose_name': 'Тип Акции',
                'verbose_name_plural': 'Тип Акции',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='promoactionproduct',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_promo_action', to='shop.PromoAction'),
        ),
    ]
