# Generated by Django 3.0.7 on 2020-06-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_ratingproduct_ratingstar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RatingProduct',
        ),
        migrations.DeleteModel(
            name='RatingStar',
        ),
    ]
