# Generated by Django 3.0.7 on 2020-06-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_productstatistic_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstatistic',
            old_name='views',
            new_name='count_views',
        ),
    ]
