# Generated by Django 3.0.7 on 2020-06-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20200619_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstatistic',
            old_name='count_views',
            new_name='count',
        ),
    ]
