# Generated by Django 3.0.7 on 2020-06-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_auto_20200619_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatistic',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
