# Generated by Django 3.0.7 on 2020-06-19 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_image'),
        ('analysis', '0006_auto_20200619_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productstatistic',
            old_name='count',
            new_name='count_views',
        ),
        migrations.RemoveField(
            model_name='productstatistic',
            name='url',
        ),
        migrations.AddField(
            model_name='productstatistic',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
            preserve_default=False,
        ),
    ]
