# Generated by Django 3.0.7 on 2020-06-19 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200619_2045'),
        ('analysis', '0007_auto_20200619_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatistic',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.Product'),
        ),
    ]
