# Generated by Django 3.0.7 on 2020-06-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20200619_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstatistic',
            name='ip_client',
            field=models.GenericIPAddressField(default=0),
            preserve_default=False,
        ),
    ]
