# Generated by Django 3.0.7 on 2020-06-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_productstatistic_ip_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatistic',
            name='ip_client',
            field=models.GenericIPAddressField(default='0'),
        ),
    ]
